UPDATE bracket
SET bracket_name = $2,
	start_time = $3, 
    start_date = $4, 
    description = $5, 
    subject = $6, 
    format = $7, 
    image_url = $8, 
    team_size = $9, 
    randomize_seeds = $10, 
    randomize_teams = $11, 
    max_teams = $12, 
    has_password = $13, 
    invite_only = $14, 
    best_of = $15, 
    finals_best_of = $16, 
    status = $17, 
    participant_type = $18
WHERE bracket_id = $1;